services:
  supabase-db:
    image: supabase/postgres:15.1.0.147
    container_name: supabase-db
    restart: always
    environment:
      POSTGRES_PASSWORD: "Password@1"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

volumes:
  supabase_data: